name: EdibleEggs
author: Smiley43210
main: com.github.smiley43210.edibleeggs.Main
version: 1.0.0.0
commands:
  edibleeggs:
    description: Reload the EdibleEggs configuration file.
    usage: /<command> reload